In [24]:
import numpy as np
import pandas as pd

In [11]:
labels = ['x','y','z']
my_list = [50,60,70]
arr = np.array([10,20,30])
d = {'x':50, 'y':20, 'z':30}

In [5]:
pd.Series(data=my_list)

0    50
1    60
2    70
dtype: int64

In [6]:
pd.Series(my_list)

0    50
1    60
2    70
dtype: int64

In [7]:
pd.Series(my_list,labels)

x    50
y    60
z    70
dtype: int64

In [8]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(arr,labels)

x    10
y    20
z    30
dtype: int64

In [12]:
pd.Series(d)

x    50
y    20
z    30
dtype: int64

In [13]:
a = [i for i in range(2,6)]
b = [i for i in range(6,10)]
c = [i for i in range(10,14)]

In [15]:
pd.DataFrame(data=[a,b,c],
index = 'a b b'.split(),
columns= 'w x y z'.split())

w   x   y   z
a   2   3   4   5
b   6   7   8   9
b  10  11  12  13

In [16]:
pd.DataFrame(data = list(zip(a,b,c)),
index = 'w x y z'.split(),
columns= 'a b c'.split())

a  b   c
w  2  6  10
x  3  7  11
y  4  8  12
z  5  9  13

In [18]:
my_list = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
pd.DataFrame(my_list, index = 'a b c'.split(), columns= 'x y z a1'.split())

x   y   z  a1
a  1   2   3   4
b  5   6   7   8
c  9  10  11  12

In [19]:
pd.DataFrame(my_list, index='a b c'.split(),columns= 'w x y z'.split()).T

a  b   c
w  1  5   9
x  2  6  10
y  3  7  11
z  4  8  12

In [26]:
from numpy.random import randn
np.random.seed(101)


In [28]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns = 'W X Y Z'.split())

In [29]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [31]:
my_d = {'x' : [1,2,3,4],
'y' : [5,6,7,8],
'z' : [9,10,11,12]}
pd.DataFrame(my_d)

x  y   z
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [33]:
pd.DataFrame(my_d, index = 'w x y z'.split())

x  y   z
w  1  5   9
x  2  6  10
y  3  7  11
z  4  8  12

In [34]:
df2 = np.arange(1,31)

In [35]:
df2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
df2.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [38]:
df2.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [39]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [40]:
df.loc['Baru'] = [1,2,3,4]

In [41]:
df

W         X         Y         Z
A     2.706850  0.628133  0.907969  0.503826
B     0.651118 -0.319318 -0.848077  0.605965
C    -2.018168  0.740122  0.528813 -0.589001
D     0.188695 -0.758872 -0.933237  0.955057
E     0.190794  1.978757  2.605967  0.683509
Baru  1.000000  2.000000  3.000000  4.000000

In [42]:
df['baru'] = df['W'] * df['Z']

In [43]:
df

W         X         Y         Z      baru
A     2.706850  0.628133  0.907969  0.503826  1.363781
B     0.651118 -0.319318 -0.848077  0.605965  0.394555
C    -2.018168  0.740122  0.528813 -0.589001  1.188702
D     0.188695 -0.758872 -0.933237  0.955057  0.180215
E     0.190794  1.978757  2.605967  0.683509  0.130410
Baru  1.000000  2.000000  3.000000  4.000000  4.000000

In [46]:
df.insert(2,'New',[1,2,3,4,5,6])

In [47]:
df

W         X  New         Y         Z      baru
A     2.706850  0.628133    1  0.907969  0.503826  1.363781
B     0.651118 -0.319318    2 -0.848077  0.605965  0.394555
C    -2.018168  0.740122    3  0.528813 -0.589001  1.188702
D     0.188695 -0.758872    4 -0.933237  0.955057  0.180215
E     0.190794  1.978757    5  2.605967  0.683509  0.130410
Baru  1.000000  2.000000    6  3.000000  4.000000  4.000000

In [48]:
df.drop('New',axis = 1)

W         X         Y         Z      baru
A     2.706850  0.628133  0.907969  0.503826  1.363781
B     0.651118 -0.319318 -0.848077  0.605965  0.394555
C    -2.018168  0.740122  0.528813 -0.589001  1.188702
D     0.188695 -0.758872 -0.933237  0.955057  0.180215
E     0.190794  1.978757  2.605967  0.683509  0.130410
Baru  1.000000  2.000000  3.000000  4.000000  4.000000

In [49]:
df

W         X  New         Y         Z      baru
A     2.706850  0.628133    1  0.907969  0.503826  1.363781
B     0.651118 -0.319318    2 -0.848077  0.605965  0.394555
C    -2.018168  0.740122    3  0.528813 -0.589001  1.188702
D     0.188695 -0.758872    4 -0.933237  0.955057  0.180215
E     0.190794  1.978757    5  2.605967  0.683509  0.130410
Baru  1.000000  2.000000    6  3.000000  4.000000  4.000000

In [50]:
df.drop('New',axis = 1, inplace=True)

In [51]:
df

W         X         Y         Z      baru
A     2.706850  0.628133  0.907969  0.503826  1.363781
B     0.651118 -0.319318 -0.848077  0.605965  0.394555
C    -2.018168  0.740122  0.528813 -0.589001  1.188702
D     0.188695 -0.758872 -0.933237  0.955057  0.180215
E     0.190794  1.978757  2.605967  0.683509  0.130410
Baru  1.000000  2.000000  3.000000  4.000000  4.000000

In [52]:
df.drop('D')

W         X         Y         Z      baru
A     2.706850  0.628133  0.907969  0.503826  1.363781
B     0.651118 -0.319318 -0.848077  0.605965  0.394555
C    -2.018168  0.740122  0.528813 -0.589001  1.188702
E     0.190794  1.978757  2.605967  0.683509  0.130410
Baru  1.000000  2.000000  3.000000  4.000000  4.000000

In [53]:
df.drop('D',inplace=True)

In [54]:
df

W         X         Y         Z      baru
A     2.706850  0.628133  0.907969  0.503826  1.363781
B     0.651118 -0.319318 -0.848077  0.605965  0.394555
C    -2.018168  0.740122  0.528813 -0.589001  1.188702
E     0.190794  1.978757  2.605967  0.683509  0.130410
Baru  1.000000  2.000000  3.000000  4.000000  4.000000

In [55]:
df

W         X         Y         Z      baru
A     2.706850  0.628133  0.907969  0.503826  1.363781
B     0.651118 -0.319318 -0.848077  0.605965  0.394555
C    -2.018168  0.740122  0.528813 -0.589001  1.188702
E     0.190794  1.978757  2.605967  0.683509  0.130410
Baru  1.000000  2.000000  3.000000  4.000000  4.000000

In [56]:
df.reset_index()

index         W         X         Y         Z      baru
0     A  2.706850  0.628133  0.907969  0.503826  1.363781
1     B  0.651118 -0.319318 -0.848077  0.605965  0.394555
2     C -2.018168  0.740122  0.528813 -0.589001  1.188702
3     E  0.190794  1.978757  2.605967  0.683509  0.130410
4  Baru  1.000000  2.000000  3.000000  4.000000  4.000000

In [57]:
buah = 'APEL JERUK MANGGA SIRSAK JAMBU'.split()
buah

['APEL', 'JERUK', 'MANGGA', 'SIRSAK', 'JAMBU']

In [58]:
df['fruit'] = buah

In [59]:
df

W         X         Y         Z      baru   fruit
A     2.706850  0.628133  0.907969  0.503826  1.363781    APEL
B     0.651118 -0.319318 -0.848077  0.605965  0.394555   JERUK
C    -2.018168  0.740122  0.528813 -0.589001  1.188702  MANGGA
E     0.190794  1.978757  2.605967  0.683509  0.130410  SIRSAK
Baru  1.000000  2.000000  3.000000  4.000000  4.000000   JAMBU

In [61]:
df

W         X         Y         Z      baru   fruit
A     2.706850  0.628133  0.907969  0.503826  1.363781    APEL
B     0.651118 -0.319318 -0.848077  0.605965  0.394555   JERUK
C    -2.018168  0.740122  0.528813 -0.589001  1.188702  MANGGA
E     0.190794  1.978757  2.605967  0.683509  0.130410  SIRSAK
Baru  1.000000  2.000000  3.000000  4.000000  4.000000   JAMBU

In [63]:
df.set_index('fruit')

W         X         Y         Z      baru
fruit                                                   
APEL    2.706850  0.628133  0.907969  0.503826  1.363781
JERUK   0.651118 -0.319318 -0.848077  0.605965  0.394555
MANGGA -2.018168  0.740122  0.528813 -0.589001  1.188702
SIRSAK  0.190794  1.978757  2.605967  0.683509  0.130410
JAMBU   1.000000  2.000000  3.000000  4.000000  4.000000

In [64]:
df.set_index('fruit',inplace=True)

In [65]:
df

W         X         Y         Z      baru
fruit                                                   
APEL    2.706850  0.628133  0.907969  0.503826  1.363781
JERUK   0.651118 -0.319318 -0.848077  0.605965  0.394555
MANGGA -2.018168  0.740122  0.528813 -0.589001  1.188702
SIRSAK  0.190794  1.978757  2.605967  0.683509  0.130410
JAMBU   1.000000  2.000000  3.000000  4.000000  4.000000